# Generated by Django 6.0.6 on 2026-06-27 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('who', models.CharField(max_length=255)),
                ('what', models.CharField(max_length=255)),
                ('kind', models.CharField(choices=[('application', 'application'), ('entry', 'entry'), ('enrollment', 'enrollment'), ('save', 'save'), ('rollout', 'rollout'), ('early-access', 'early-access'), ('gate-action', 'gate-action'), ('judgment', 'judgment'), ('team-match', 'team-match'), ('certificate-issued', 'certificate-issued')], max_length=30)),
                ('occurred_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
    ]
