# Generated by Django 6.0.6 on 2026-06-30 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='kind',
            field=models.CharField(choices=[('application', 'application'), ('entry', 'entry'), ('enrollment', 'enrollment'), ('save', 'save'), ('rollout', 'rollout'), ('early-access', 'early-access'), ('gate-action', 'gate-action'), ('judgment', 'judgment'), ('team-match', 'team-match'), ('certificate-issued', 'certificate-issued'), ('contest-result', 'contest-result')], max_length=30),
        ),
    ]
