# Generated by Django 6.0.6 on 2026-07-01 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_add_occurred_at_index'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='activitylog',
            name='activity_log_occurred_at_idx',
        ),
    ]
