# Generated by Django 6.0.6 on 2026-07-02 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0004_remove_activitylog_activity_log_occurred_at_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['-occurred_at'], name='activity_occurred_at_desc'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['kind', '-occurred_at'], name='activity_kind_occurred_at'),
        ),
    ]
