# Generated by Django 6.0.6 on 2026-06-30 07:14

import apps.accounts.models
from django.db import migrations, models


def copy_academy_users_and_block_old(apps, schema_editor):
    """One-time data migration: every existing accounts.User with role in
    (student, facilitator, judge) gets a matching AcademyUser row, same id
    preserved so every existing Academy FK (enrollment, judgment, team,
    cohort.facilitator, roster_request.facilitator) still resolves to the
    right person once those FKs retarget to AcademyUser in the next
    migration. The old accounts.User row is then blocked (not deleted) so
    the legacy /api/auth/local path stops accepting it, closing off a
    confusing dual-login path with the same password."""
    User = apps.get_model("accounts", "User")
    AcademyUser = apps.get_model("accounts", "AcademyUser")

    for u in User.objects.filter(role__in=["student", "facilitator", "judge"]):
        AcademyUser.objects.create(
            id=u.id,
            username=u.username,
            email=u.email,
            password=u.password,
            name=u.name,
            whatsapp=u.whatsapp,
            role=u.role,
            confirmed=u.confirmed,
            blocked=u.blocked,
            is_active=u.is_active,
            created_at=u.created_at,
            updated_at=u.updated_at,
        )
        u.blocked = True
        u.save(update_fields=["blocked"])

    # Postgres's sequence has no idea about these explicit-PK inserts —
    # without this, the first self-registered AcademyUser after this
    # migration collides with a migrated id and 500s on IntegrityError.
    schema_editor.execute(
        "SELECT setval(pg_get_serial_sequence('accounts_academyuser', 'id'), "
        "COALESCE((SELECT MAX(id) FROM accounts_academyuser), 1))"
    )


def unblock_and_delete_academy_users(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    AcademyUser = apps.get_model("accounts", "AcademyUser")
    migrated_ids = list(AcademyUser.objects.values_list("id", flat=True))
    User.objects.filter(id__in=migrated_ids).update(blocked=False)
    AcademyUser.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(blank=True, max_length=150)),
                ('whatsapp', models.CharField(blank=True, max_length=32)),
                ('role', models.CharField(choices=[('student', 'Student'), ('facilitator', 'Facilitator'), ('judge', 'Judge')], default='student', max_length=20)),
                ('confirmed', models.BooleanField(default=True)),
                ('blocked', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', apps.accounts.models.AcademyUserManager()),
            ],
        ),
        migrations.RunPython(copy_academy_users_and_block_old, reverse_code=unblock_and_delete_academy_users),
    ]
