# Generated by Django 6.0.6 on 2026-06-28 11:44

import apps.academy.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('blurb', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'academy categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AcademyCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('months', models.PositiveIntegerField()),
                ('certificate', models.BooleanField(default=False)),
                ('weeks_total', models.PositiveIntegerField()),
                ('days_total', models.PositiveIntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='academy.academycategory')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='AcademyCohort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('weeks_total', models.PositiveIntegerField()),
                ('days_total', models.PositiveIntegerField()),
                ('start_date', models.DateField()),
                ('status', models.CharField(choices=[('Enrolling', 'Enrolling'), ('Running', 'Running'), ('Completed', 'Completed')], default='Enrolling', max_length=20)),
                ('released_week', models.PositiveIntegerField(default=0)),
                ('min_completion', models.PositiveIntegerField(default=60)),
                ('check_weeks', models.JSONField(default=list)),
                ('facilitator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facilitated_cohorts', to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cohorts', to='academy.academycourse')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='AcademyEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('In progress', 'In progress'), ('Starting soon', 'Starting soon'), ('Completed', 'Completed')], default='Starting soon', max_length=20)),
                ('current_day', models.PositiveIntegerField(default=1)),
                ('submitted_days', models.JSONField(default=list)),
                ('early_access_requested', models.BooleanField(default=False)),
                ('early_weeks', models.JSONField(default=list)),
                ('removed', models.BooleanField(default=False)),
                ('shortlisted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='academy.academycohort')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academy_enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'cohort')},
            },
        ),
        migrations.CreateModel(
            name='AcademyCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_code', models.CharField(default=apps.academy.models._generate_verification_code, max_length=32, unique=True)),
                ('issued_at', models.DateTimeField()),
                ('student_name_snapshot', models.CharField(max_length=255)),
                ('course_title_snapshot', models.CharField(max_length=255)),
                ('cohort_name_snapshot', models.CharField(max_length=255)),
                ('pdf_url', models.URLField(blank=True)),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='academy.academyenrollment')),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='AcademyMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveIntegerField()),
                ('text', models.TextField(blank=True)),
                ('external_video_url', models.URLField(blank=True)),
                ('mux_upload_id', models.CharField(blank=True, max_length=255)),
                ('mux_asset_id', models.CharField(blank=True, max_length=255)),
                ('mux_playback_id', models.CharField(blank=True, max_length=255)),
                ('task', models.CharField(blank=True, max_length=255)),
                ('task_detail', models.TextField(blank=True)),
                ('docs', models.JSONField(blank=True, default=list)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='academy.academycourse')),
            ],
            options={
                'ordering': ['day'],
                'unique_together': {('course', 'day')},
            },
        ),
    ]
