# Generated by Django 6.0.6 on 2026-06-28 11:47

import apps.academy.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academycohort',
            name='check_weeks',
            field=models.JSONField(default=apps.academy.models._default_check_weeks),
        ),
    ]
