# Generated by Django 6.0.6 on 2026-06-28 12:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0002_alter_academycohort_check_weeks'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='academyenrollment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='AcademyLiveSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('Live call', 'Live call'), ('Workshop', 'Workshop')], max_length=20)),
                ('day', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=50)),
                ('host', models.CharField(max_length=255)),
                ('link', models.URLField(blank=True)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='academy.academycohort')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AcademyRosterRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Fulfilled', 'Fulfilled'), ('Dismissed', 'Dismissed')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roster_requests', to='academy.academycohort')),
                ('facilitator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roster_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AcademySubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveIntegerField()),
                ('week', models.PositiveIntegerField()),
                ('task', models.CharField(max_length=255)),
                ('course_title', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('note', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField()),
                ('rated', models.BooleanField(default=False)),
                ('anon_handle', models.CharField(max_length=32, unique=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='academy.academyenrollment')),
            ],
            options={
                'ordering': ['-day'],
            },
        ),
        migrations.CreateModel(
            name='AcademyTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='academy.academycohort')),
                ('members', models.ManyToManyField(blank=True, related_name='academy_teams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='AcademyJudgment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brief', models.PositiveSmallIntegerField()),
                ('craft', models.PositiveSmallIntegerField()),
                ('originality', models.PositiveSmallIntegerField()),
                ('average', models.DecimalField(decimal_places=2, max_digits=4)),
                ('feedback', models.TextField()),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academy_judgments', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judgments', to='academy.academysubmission')),
            ],
            options={
                'ordering': ['-id'],
                'unique_together': {('submission', 'judge')},
            },
        ),
    ]
