# Generated by Django 6.0.6 on 2026-06-30 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0004_academycohort_capacity_academyapplication'),
        ('accounts', '0002_academyuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academyapplication',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academy_applications', to='accounts.academyuser'),
        ),
        migrations.AlterField(
            model_name='academycohort',
            name='facilitator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facilitated_cohorts', to='accounts.academyuser'),
        ),
        migrations.AlterField(
            model_name='academyenrollment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academy_enrollments', to='accounts.academyuser'),
        ),
        migrations.AlterField(
            model_name='academyjudgment',
            name='judge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academy_judgments', to='accounts.academyuser'),
        ),
        migrations.AlterField(
            model_name='academyrosterrequest',
            name='facilitator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roster_requests', to='accounts.academyuser'),
        ),
        migrations.AlterField(
            model_name='academyteam',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='academy_teams', to='accounts.academyuser'),
        ),
    ]
