# Generated by Django 6.0.6 on 2026-07-02 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0005_alter_academyapplication_user_and_more'),
        ('accounts', '0002_academyuser'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='academyapplication',
            index=models.Index(fields=['course', 'status', 'created_at'], name='acad_app_course_status_at'),
        ),
        migrations.AddIndex(
            model_name='academycohort',
            index=models.Index(fields=['course', 'status', 'start_date'], name='acad_cohort_course_status'),
        ),
        migrations.AddIndex(
            model_name='academyenrollment',
            index=models.Index(fields=['cohort', 'removed'], name='acad_enroll_cohort_removed'),
        ),
        migrations.AddIndex(
            model_name='academysubmission',
            index=models.Index(fields=['rated', 'submitted_at'], name='acad_sub_rated_submitted_at'),
        ),
    ]
