# Generated by Django 6.0.6 on 2026-06-27 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('kind', models.CharField(choices=[('Sister business', 'Sister business'), ('Partner', 'Partner')], max_length=20)),
                ('industry', models.CharField(max_length=255)),
                ('tagline', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('featured', models.BooleanField(default=False)),
                ('seed', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('field', models.CharField(choices=[('Digital', 'Digital'), ('Technical', 'Technical'), ('Craft', 'Craft'), ('Creative', 'Creative')], max_length=20)),
                ('brief', models.TextField()),
                ('rules', models.JSONField(default=list)),
                ('deadline', models.DateTimeField()),
                ('status', models.CharField(choices=[('live', 'live'), ('past', 'past')], default='live', max_length=20)),
                ('entries', models.PositiveIntegerField(default=0)),
                ('seed', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('field', models.CharField(choices=[('Digital', 'Digital'), ('Technical', 'Technical'), ('Craft', 'Craft'), ('Creative', 'Creative')], max_length=20)),
                ('level', models.CharField(choices=[('Entry', 'Entry'), ('Mid', 'Mid'), ('Senior', 'Senior')], max_length=20)),
                ('kind', models.CharField(choices=[('Course', 'Course'), ('Certification', 'Certification')], max_length=20)),
                ('delivery', models.CharField(choices=[('Online', 'Online'), ('Onsite', 'Onsite'), ('Hybrid', 'Hybrid')], max_length=20)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('instructor', models.CharField(max_length=255)),
                ('instructor_role', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('weeks', models.PositiveIntegerField()),
                ('blurb', models.TextField()),
                ('outcomes', models.JSONField(default=list)),
                ('seed', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('org', models.CharField(max_length=255)),
                ('org_kind', models.CharField(max_length=255)),
                ('field', models.CharField(choices=[('Digital', 'Digital'), ('Technical', 'Technical'), ('Craft', 'Craft'), ('Creative', 'Creative')], max_length=20)),
                ('location', models.CharField(max_length=255)),
                ('location_type', models.CharField(choices=[('Remote', 'Remote'), ('Onsite', 'Onsite'), ('Hybrid', 'Hybrid')], max_length=20)),
                ('type', models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Contract', 'Contract')], max_length=20)),
                ('level', models.CharField(choices=[('Entry', 'Entry'), ('Mid', 'Mid'), ('Senior', 'Senior')], max_length=20)),
                ('pay', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('responsibilities', models.JSONField(default=list)),
                ('requirements', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('draft', 'draft'), ('published', 'published'), ('closed', 'closed')], default='published', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('category', models.CharField(choices=[('Apparel', 'Apparel'), ('Accessories', 'Accessories'), ('Electronics', 'Electronics'), ('Tools', 'Tools'), ('Furniture', 'Furniture'), ('Home', 'Home')], max_length=20)),
                ('type', models.CharField(choices=[('Tee', 'Tee'), ('Sweatshirt', 'Sweatshirt'), ('Hoodie', 'Hoodie'), ('Apron', 'Apron'), ('Cap', 'Cap'), ('Tote', 'Tote'), ('Sticker', 'Sticker'), ('Laptop', 'Laptop'), ('Phone', 'Phone'), ('Tablet', 'Tablet'), ('Monitor', 'Monitor'), ('Headphones', 'Headphones'), ('Keyboard', 'Keyboard'), ('Charger', 'Charger'), ('Drill', 'Drill'), ('Toolkit', 'Toolkit'), ('Mug', 'Mug'), ('Notebook', 'Notebook'), ('Desk', 'Desk'), ('Stool', 'Stool'), ('Shelf', 'Shelf')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('blurb', models.TextField()),
                ('details', models.JSONField(default=list)),
                ('sizes', models.JSONField(blank=True, default=list)),
                ('maker', models.CharField(blank=True, max_length=255)),
                ('condition', models.CharField(choices=[('New', 'New'), ('Used', 'Used'), ('Refurbished', 'Refurbished')], default='New', max_length=20)),
                ('brand', models.CharField(blank=True, max_length=255)),
                ('shopify_url', models.URLField()),
                ('seed', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField()),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='marketplace.course')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.PositiveIntegerField()),
                ('label', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prizes', to='marketplace.contest')),
            ],
            options={
                'ordering': ['place'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('duration', models.CharField(max_length=50)),
                ('free', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='marketplace.module')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('module', 'key')},
            },
        ),
    ]
