# Generated by Django 6.0.6 on 2026-07-01 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_add_status_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='contest',
            name='marketplace_contest_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='job',
            name='marketplace_job_status_idx',
        ),
    ]
